# A description of numpy (Don't read everything, just know it's there.)

In [71]:
import numpy as np

print(np.__doc__[:188])


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation




# Numpy is probably the fastest computational package you'll ever use.

# You can also find numpy documentation online

In [31]:
import webbrowser as wb
wb.open("http://www.scipy.org")

True

# Using Numpy


# Initializing an array

Before using numpy, you'll need to import it, as shown below.

In [1]:
import numpy as np

You'll need to use ```np.array()``` function to make an array. Then, pass a list as input that you would like converted into an array.

In [6]:
x = np.array([34, 73, 28, 81, 95])

In [7]:
x

array([34, 73, 28, 81, 95])

# Subtraction and Addition

In [12]:
x = np.array([34, 73, 28, 81, 95])

In [13]:
x - 34

array([ 0, 39, -6, 47, 61])

In [14]:
x + 81

array([115, 154, 109, 162, 176])

# Multiplication and Division

In [10]:
x * 100

array([3400, 7300, 2800, 8100, 9500])

In [11]:
x / 100

array([0.34, 0.73, 0.28, 0.81, 0.95])

# What about matrix multiplication? (@)

In [33]:
A = np.eye(3)
A

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
x = np.array([5, 4, 2]).reshape(3, 1)

In [42]:
A @ x

array([[5.],
       [4.],
       [2.]])

## which is not the same as element-wise multiplication ( * ) 

In [43]:
x = np.array([5, 4, 2]).reshape(3, 1)

x.transpose() * x    # element-wise product

array([[25, 20, 10],
       [20, 16,  8],
       [10,  8,  4]])

In [44]:
x.transpose() @ x    # Same as dot product

array([[45]])

# np.arange

In [15]:
x = np.arange(20)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [19]:
n = np.arange(0, 100, 5) #start, stop, step!
n

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

# ndarray.reshape()

In [16]:
x.reshape(4, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

# What is x?

In [20]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

Remember, we need to use variable assignment (```x = something```) in order to change what we store in the variable name ```x```.

In [21]:
x = x.reshape(4, 5)

In [22]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

# ndarray.transpose()

In [23]:
x.transpose()

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

# Np.Random gives pseudorandom numbers

In [51]:
matrix = np.random.randint(0, 5, (4, 5))

In [52]:
matrix

array([[3, 4, 1, 4, 2],
       [1, 0, 2, 1, 1],
       [2, 2, 4, 4, 0],
       [1, 0, 4, 1, 4]])

# Shape, Size, and indexing

In [61]:
matrix.size

20

In [54]:
matrix.shape

(4, 5)

In [55]:
matrix.shape = (2, 10)
matrix

array([[3, 4, 1, 4, 2, 1, 0, 2, 1, 1],
       [2, 2, 4, 4, 0, 1, 0, 4, 1, 4]])

In [56]:
matrix[0]

array([3, 4, 1, 4, 2, 1, 0, 2, 1, 1])

In [64]:
matrix

array([[3, 4, 1, 4, 2, 1, 0, 2, 1, 1],
       [2, 2, 4, 4, 0, 1, 0, 4, 1, 4]])

In [65]:
matrix[0,4:8]

array([2, 1, 0, 2])

In [63]:
matrix

array([[3, 4, 1, 4, 2, 1, 0, 2, 1, 1],
       [2, 2, 4, 4, 0, 1, 0, 4, 1, 4]])

In [62]:
matrix[:,:2]

array([[3, 4],
       [2, 2]])

When indexing, think ```array[row, column]```. You'll need this a lot

# How many dimensions?

In [60]:
# However many you like!

x = np.arange(400)
x.reshape(4, 5, 2, 2, 5)

array([[[[[  0,   1,   2,   3,   4],
          [  5,   6,   7,   8,   9]],

         [[ 10,  11,  12,  13,  14],
          [ 15,  16,  17,  18,  19]]],


        [[[ 20,  21,  22,  23,  24],
          [ 25,  26,  27,  28,  29]],

         [[ 30,  31,  32,  33,  34],
          [ 35,  36,  37,  38,  39]]],


        [[[ 40,  41,  42,  43,  44],
          [ 45,  46,  47,  48,  49]],

         [[ 50,  51,  52,  53,  54],
          [ 55,  56,  57,  58,  59]]],


        [[[ 60,  61,  62,  63,  64],
          [ 65,  66,  67,  68,  69]],

         [[ 70,  71,  72,  73,  74],
          [ 75,  76,  77,  78,  79]]],


        [[[ 80,  81,  82,  83,  84],
          [ 85,  86,  87,  88,  89]],

         [[ 90,  91,  92,  93,  94],
          [ 95,  96,  97,  98,  99]]]],



       [[[[100, 101, 102, 103, 104],
          [105, 106, 107, 108, 109]],

         [[110, 111, 112, 113, 114],
          [115, 116, 117, 118, 119]]],


        [[[120, 121, 122, 123, 124],
          [125, 126, 127, 128, 129]],

# What else is in numpy?

In [29]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'PackageLoader',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_distributor_init',
 '_globals',
 '_import_tools

# So much that there's no need to memorize. Just Google as you go.

If you want to learn more, here's a tutorial if you want to learn numpy really well! (Not to be done in one evening)

https://www.tutorialspoint.com/numpy

